### ISSUE TITLE
Modbus support

### ISSUE THREAD

**Issue by Uskompuf** [drobtravels/solaredge-local#13]
Hi just wondering does the api support getting modbus data?

Thanks

**Comment by drobtravels** [comment]
There are several modbus related endpoints (see README).  I'm not familiar with the modbus format so I'm not clear if this is just to set up communication via modbus, or actually retrieve modbus data. 


web/v1/communication/modbus_tcp might be what you're looking for.  

Let me know if I can provide any guidance on how to explore this.

**Comment by Uskompuf** [comment]
Sorry,

completely missed that.
