### ISSUE TITLE
Module doesn't import

### ISSUE THREAD

**Issue by AndyRPH** [drobtravels/solaredge-local#5]
Getting errors when I try to install it.

 pi@rpisink:~ $pip install solaredge-local
Collecting solaredge-local
  Downloading https://files.pythonhosted.org/packages/ff/f1/e467c9c90d5d25cc2e4ce3c5ef27297f13bda623edab1fd2fef7748f4644/solaredge_local-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-18A4IY/solaredge-local/setup.py", line 8, in <module>
        import solaredge_local
      File "solaredge_local/__init__.py", line 1, in <module>
        from solaredge_local.solaredge import SolarEdge
      File "solaredge_local/solaredge.py", line 7
        def get_status(self) -> Status:
                             ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-18A4IY/solaredge-local/
pi@rpisink:~ $

**Comment by AndyRPH** [comment]
More verbose error log:

pi@rpisink:~ $ pip install solaredge-local -vvv
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Collecting solaredge-local
  2 location(s) to search for versions of solaredge-local:
  * https://pypi.python.org/simple/solaredge-local/
  * https://www.piwheels.org/simple/solaredge-local/
  Getting page https://pypi.python.org/simple/solaredge-local/
  Looking up "https://pypi.python.org/simple/solaredge-local/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/solaredge-local/" in the cache  Current age based on date: 1442
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/solaredge-local/ HTTP/1.1" 304 0  Analyzing links from page https://pypi.org/simple/solaredge-local/    Skipping link https://files.pythonhosted.org/packages/43/80/8ed99770cafd36468247d0e9a50cd3ae7f142f1e180d708fc7b5398d3bc3/solaredge_local-0.1.0-py3-none-any.whl#sha256=3131a2cf061e53eddd11a8e45ee5044afab77c82dd8830095059a584d392868d (from https://pypi.org/simple/solaredge-local/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/30/00/5a368bb0158759b8ce4ef0c839c18f41c9624bb8dd99bd26b7b28536241d/solaredge_local-0.1.0.tar.gz#sha256=330e45ba94c36d70c6f494e4874089c9f01330fb700c5e2c3c6afda91cdd6beb (from https://pypi.org/simple/solaredge-local/), version: 0.1.0
    Skipping link https://files.pythonhosted.org/packages/4a/30/ae4a40825ebb6968cf9ac87f867877347f69d46d1bc7bba3e40503a26f11/solaredge_local-0.1.1-py3-none-any.whl#sha256=ca78f23ef2403d8aaa931543c01b7636b24019e9aa7efce160ca8bd855e48353 (from https://pypi.org/simple/solaredge-local/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/ff/f1/e467c9c90d5d25cc2e4ce3c5ef27297f13bda623edab1fd2fef7748f4644/solaredge_local-0.1.1.tar.gz#sha256=e26e94636554bdd5eb60e89577ece459b93fcc3bc13226626d21bc6071b1bd11 (from https://pypi.org/simple/solaredge-local/), version: 0.1.1
  Getting page https://www.piwheels.org/simple/solaredge-local/
  Looking up "https://www.piwheels.org/simple/solaredge-local/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): www.piwheels.org
  https://www.piwheels.org:443 "GET /simple/solaredge-local/ HTTP/1.1" 404 306
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://www.piwheels.org/simple/solaredge-local/: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/solaredge-local/ - skipping
  Using version 0.1.1 (newest of versions: 0.1.0, 0.1.1)
  Looking up "https://files.pythonhosted.org/packages/ff/f1/e467c9c90d5d25cc2e4ce3c5ef27297f13bda623edab1fd2fef7748f4644/solaredge_local-0.1.1.tar.gz" in the cache
  Current age based on date: 1442
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 1442
  Using cached https://files.pythonhosted.org/packages/ff/f1/e467c9c90d5d25cc2e4ce3c5ef27297f13bda623edab1fd2fef7748f4644/solaredge_local-0.1.1.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/ff/f1/e467c9c90d5d25cc2e4ce3c5ef27297f13bda623edab1fd2fef7748f4644/solaredge_local-0.1.1.tar.gz#sha256=e26e94636554bdd5eb60e89577ece459b93fcc3bc13226626d21bc6071b1bd11 (from https://pypi.org/simple/solaredge-local/)
  Running setup.py (path:/tmp/pip-build-D51Ddv/solaredge-local/setup.py) egg_info for package solaredge-local
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-D51Ddv/solaredge-local/setup.py", line 8, in <module>
        import solaredge_local
      File "solaredge_local/__init__.py", line 1, in <module>
        from solaredge_local.solaredge import SolarEdge
      File "solaredge_local/solaredge.py", line 7
        def get_status(self) -> Status:
                             ^
    SyntaxError: invalid syntax
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-D51Ddv/solaredge-local/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 725, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-D51Ddv/solaredge-local/
pi@rpisink:~ $

**Comment by drobtravels** [comment]
Looks like you're using python 2.7. Can you try with python 3? I should have documented that.

**Comment by AndyRPH** [comment]
Ah, yeah just a stock raspbian image.  Python 3 worked.  Thanks!
