### ISSUE TITLE
Wrong data types in status.proto?

### ISSUE THREAD

**Issue by Jandokus** [drobtravels/solaredge-local#7]
I have decrypted some binary messages of status messages and I think some of the data types are not right in the status.proto file. Because I am not so familiar with GitHub I post them here:
- switchStatus: string must be a bool;
- fan: string must be a int32;
- subSystem: string must be a int32;
- portiaErrorCode: string must be a int32;
- portiaSubsystem: string must be a int32;

Hopefully somebody can test my findings and wil update status.proto!

**Comment by drobtravels** [comment]
Thanks for reporting!  I just tested and updated
