### ISSUE TITLE
Isolation data missing

### ISSUE THREAD

**Issue by rubenelshof** [drobtravels/solaredge-local#9]
Hello,

I have installed the python wrapper.
I tried to get isolation value but it appears to be missing from https://github.com/drobtravels/solaredge-local/blob/master/solaredge_local/maintenance_pb2.py

**Comment by drobtravels** [comment]
I'm not at all familiar with the Isolation data.  I spent 30 minutes looking at it, but wasn't clear.

The Isolation data appears to look like this

```
3 {
        1 {
          1: 5000
          2: 100
        }
        2 {
          1: 1100000
          2: 100
        }
        3: 10
      }
```

With 1 being alpha, 2 being rIso, and 3 being faultLocation.  I'm not sure what the sub-values are.  It appears in the JS source for the website under `Maintenance.Diagnostics.Inverters.Unit.Isolation`

If you could help correct the `maintenance.proto` file and test using `curl` that be appreciated.

**Comment by rubenelshof** [comment]
rIso 1 gives the Isolation value in kOhm's. I cannot find what the values under Alpha mean. For rIso and Alpha the second value (100) is scaling.

Fault location seems always to be 10 if there are no errors. As stated here https://www.solaredge.com/sites/default/files/application_note_isolation_fault_troubleshooting.pdf 

I have created a pull request with only the Isolation value and Fault location.
